name: Update Fork

on:
  push:
    branches:
      - main

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with Fork
        run: |
          git config --global user.name 'bbung'
          git config --global user.email 'tjd123123@naver.com'
          git remote add fork ${{ secrets.SYNC_REPO}}
          git fetch fork
          git checkout main
          git merge --allow-unrelated-histories fork/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
